apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: template  # replace with your actual namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30081  # This is the port that will be exposed on each node
