apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: template  # replace with your actual namespace
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001  # This is the port that will be exposed on each node
